name: atheon_ui
description: Flutter UI for Atheon
version: 0.1.1
homepage: https://github.com/atheon-inc/atheon-codex-dart
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  device_info_plus: ^12.3.0
  flutter_svg: ^2.2.3
  flutter_markdown_plus: ^1.0.7
  markdown: ^7.3.0
  uuid: ^4.5.2
  package_info_plus: ^9.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_lints: ^6.0.0
